In [1]:
import numpy as np

In [2]:
# Setting the random seed, feel free to change it and see different solutions.
np.random.seed(42)

In [3]:
def stepFunction(t):
    if t >= 0:
        return 1
    return 0

In [4]:
def prediction(X, W, b):
    return stepFunction((np.matmul(X,W)+b)[0])

In [66]:
# TODO: Fill in the code below to implement the perceptron trick.
# The function should receive as inputs the data X, the labels y,
# the weights W (as an array), and the bias b,
# update the weights and bias W, b, according to the perceptron algorithm,
# and return W and b.
def perceptronStep(X, y, W, b, learn_rate = 0.01):
    # Fill in code
    for i in range(X.shape[0]):
        y_hat = prediction(X[i], W, b)
        if y_hat != y[i] and y_hat == 0:
            W += (X[i] * learn_rate).reshape(W.shape)
            b += learn_rate
        elif y_hat != y[i] and y_hat == 1:
            W -= (X[i] * learn_rate).reshape(W.shape)
            b -= learn_rate
    return W, b    

In [67]:
# This function runs the perceptron algorithm repeatedly on the dataset,
# and returns a few of the boundary lines obtained in the iterations,
# for plotting purposes.
# Feel free to play with the learning rate and the num_epochs,
# and see your results plotted below.
def trainPerceptronAlgorithm(X, y, learn_rate = 0.01, num_epochs = 25):
    x_min, x_max = min(X.T[0]), max(X.T[0])
    y_min, y_max = min(X.T[1]), max(X.T[1])
    W = np.array(np.random.rand(2,1))
    b = np.random.rand(1)[0] + x_max
    # These are the solution lines that get plotted below.
    boundary_lines = []
    for i in range(num_epochs):
        # In each epoch, we apply the perceptron step.
        W, b = perceptronStep(X, y, W, b, learn_rate)
        boundary_lines.append((-W[0]/W[1], -b/W[1]))
    return boundary_lines

In [68]:
import pandas as pd

In [69]:
data = pd.read_csv('11_data.csv', names=['x1', 'x2', 'y'])

In [70]:
data.tail()

x1       x2  y
95  0.77029  0.70140  0
96  0.73156  0.71782  0
97  0.44556  0.57991  0
98  0.85275  0.85987  0
99  0.51912  0.62359  0

In [71]:
trainPerceptronAlgorithm(X, y)

[(array([3.5679513]), array([4.97079108])),
 (array([0.3425572]), array([0.42998433])),
 (array([0.24930367]), array([0.33090314])),
 (array([0.20269105]), array([0.35539945])),
 (array([0.1693971]), array([0.38177774])),
 (array([0.12333581]), array([0.38388612])),
 (array([0.09695899]), array([0.41300582])),
 (array([0.05955739]), array([0.41742306])),
 (array([0.03447816]), array([0.44843148])),
 (array([0.00483292]), array([0.45383676])),
 (array([-0.02553571]), array([0.45937393])),
 (array([-0.05117847]), array([0.46397324])),
 (array([-0.06851791]), array([0.49903297])),
 (array([-0.09485408]), array([0.50563539])),
 (array([-0.12189648]), array([0.51241485])),
 (array([-0.14967388]), array([0.51937859])),
 (array([-0.17821668]), array([0.5265342])),
 (array([-0.19952008]), array([0.5322499])),
 (array([-0.22129106]), array([0.53809104])),
 (array([-0.23412324]), array([0.57779364])),
 (array([-0.25643702]), array([0.58577517])),
 (array([-0.27937592]), array([0.5939803])),
 (ar